-- MySQL Script generated by MySQL Workbench
-- 05/22/17 16:18:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema peliculasLee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `peliculasLee` ;

-- -----------------------------------------------------
-- Schema peliculasLee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peliculasLee` DEFAULT CHARACTER SET utf8 ;
USE `peliculasLee` ;

-- -----------------------------------------------------
-- Table `peliculasLee`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasLee`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `peliculasLee`.`usuarios` (
    `username` VARCHAR(45) NOT NULL,
    `password` VARCHAR(45) NULL,
    `nombre` VARCHAR(45) NULL,
    `apellidos` VARCHAR(45) NULL,
    `email` VARCHAR(45) NULL,
    `imagen` VARCHAR(45) NULL,
    PRIMARY KEY (`username`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `peliculasLee`.`administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasLee`.`administradores` ;

CREATE TABLE IF NOT EXISTS `peliculasLee`.`administradores` (
    `username` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`username`),
    CONSTRAINT `fk_administradores_usuarios1` FOREIGN KEY (`username`)
        REFERENCES `peliculasLee`.`usuarios` (`username`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `peliculasLee`.`peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasLee`.`peliculas` ;

CREATE TABLE IF NOT EXISTS `peliculasLee`.`peliculas` (
    `idPelicula` INT NOT NULL AUTO_INCREMENT,
    `titulo` VARCHAR(45) NULL,
    `sinopsis` VARCHAR(2000) NULL,
    `anio` INT(4) NULL,
    `director` VARCHAR(45) NULL,
    `reparto` VARCHAR(2000) NULL,
    `username` VARCHAR(45) NOT NULL,
    `fechaCreacion` DATE NULL,
    PRIMARY KEY (`idPelicula`),
    INDEX `fk_peliculas_administradores1_idx` (`username` ASC),
    CONSTRAINT `fk_peliculas_administradores1` FOREIGN KEY (`username`)
        REFERENCES `peliculasLee`.`administradores` (`username`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `peliculasLee`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasLee`.`categorias` ;

CREATE TABLE IF NOT EXISTS `peliculasLee`.`categorias` (
    `idCategoria` INT NOT NULL AUTO_INCREMENT,
    `descripcion` VARCHAR(45) NULL,
    PRIMARY KEY (`idCategoria`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `peliculasLee`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasLee`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `peliculasLee`.`comentarios` (
    `idPelicula` INT NOT NULL,
    `username` VARCHAR(45) NOT NULL,
    `comentario` VARCHAR(500) NULL,
    PRIMARY KEY (`idPelicula` , `username`),
    INDEX `fk_peliculas_has_usuarios_usuarios1_idx` (`username` ASC),
    INDEX `fk_peliculas_has_usuarios_peliculas1_idx` (`idPelicula` ASC),
    CONSTRAINT `fk_peliculas_has_usuarios_peliculas1` FOREIGN KEY (`idPelicula`)
        REFERENCES `peliculasLee`.`peliculas` (`idPelicula`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_peliculas_has_usuarios_usuarios1` FOREIGN KEY (`username`)
        REFERENCES `peliculasLee`.`usuarios` (`username`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `peliculasLee`.`valoraciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasLee`.`valoraciones` ;

CREATE TABLE IF NOT EXISTS `peliculasLee`.`valoraciones` (
    `idPelicula` INT NOT NULL,
    `username` VARCHAR(45) NOT NULL,
    `valoracion` INT NULL,
    PRIMARY KEY (`idPelicula` , `username`),
    INDEX `fk_peliculas_has_usuarios1_usuarios1_idx` (`username` ASC),
    INDEX `fk_peliculas_has_usuarios1_peliculas1_idx` (`idPelicula` ASC),
    CONSTRAINT `fk_peliculas_has_usuarios1_peliculas1` FOREIGN KEY (`idPelicula`)
        REFERENCES `peliculasLee`.`peliculas` (`idPelicula`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_peliculas_has_usuarios1_usuarios1` FOREIGN KEY (`username`)
        REFERENCES `peliculasLee`.`usuarios` (`username`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `peliculasLee`.`categoriasPorPelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculasLee`.`categoriasPorPelicula` ;

CREATE TABLE IF NOT EXISTS `peliculasLee`.`categoriasPorPelicula` (
    `idPelicula` INT NOT NULL,
    `idCategoria` INT NOT NULL,
    PRIMARY KEY (`idPelicula` , `idCategoria`),
    INDEX `fk_peliculas_has_categorias_categorias1_idx` (`idCategoria` ASC),
    INDEX `fk_peliculas_has_categorias_peliculas1_idx` (`idPelicula` ASC),
    CONSTRAINT `fk_peliculas_has_categorias_peliculas1` FOREIGN KEY (`idPelicula`)
        REFERENCES `peliculasLee`.`peliculas` (`idPelicula`)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_peliculas_has_categorias_categorias1` FOREIGN KEY (`idCategoria`)
        REFERENCES `peliculasLee`.`categorias` (`idCategoria`)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
